-- Fix: Convert guide bodies from Markdown to HTML
-- v1.20.42.18.5.0 Phase 8 fix
UPDATE guides SET body = '<h2>地址格式</h2><p>加拿大地址通常按以下顺序书写：</p><pre>收件人姓名
门牌号 街道名
城市, 省份缩写 邮编
CANADA</pre><pre>Zhang San
1234 Main Street
Toronto, ON M4B 1B3
CANADA</pre><h2>邮编格式</h2><p>加拿大邮编格式为 <strong>A1A 1A1</strong>：</p><ul><li>字母-数字-字母 + 空格 + 数字-字母-数字</li><li>前三个字符为 Forward Sortation Area (FSA)</li><li>后三个字符为 Local Delivery Unit (LDU)</li></ul><h2>省份缩写</h2><table class="guide-table"><tr><td>Ontario</td><td>ON</td></tr><tr><td>British Columbia</td><td>BC</td></tr><tr><td>Quebec</td><td>QC</td></tr><tr><td>Alberta</td><td>AB</td></tr><tr><td>Manitoba</td><td>MB</td></tr><tr><td>Saskatchewan</td><td>SK</td></tr><tr><td>Nova Scotia</td><td>NS</td></tr><tr><td>New Brunswick</td><td>NB</td></tr></table><h2>常见注意事项</h2><ul><li>邮编中的字母必须大写</li><li>邮编中间有一个空格</li><li>省份必须使用两字母缩写</li><li>国际包裹建议在最后一行写明 CANADA</li></ul><blockquote>⚠️ 免责声明：以上信息仅供参考，请以加拿大邮政（Canada Post）官方规定为准。</blockquote><h2>相关工具</h2><ul><li><a href="/tools/postal-code">邮编格式校验工具</a> — 验证加拿大邮编格式</li><li><a href="/tools/address-formatter">地址格式化工具</a> — 一键生成标准地址</li></ul><h2>相关指南</h2><ul><li><a href="/guides/shipping-from-china-to-canada-guide">中国寄加拿大完整流程</a></li><li><a href="/guides/commercial-invoice-guide">商业发票填写指南</a></li></ul><h2>相关清单</h2><ul><li><a href="/checklists/canada-shipping-checklist">中国寄加拿大 8 步清单</a></li><li><a href="/checklists/export-documents-checklist">发货前资料检查清单</a></li></ul>' WHERE slug = 'canada-address-format';
UPDATE guides SET body = '<h2>什么是商业发票</h2><p>商业发票（Commercial Invoice）是国际贸易中的核心单据，用于报关、清关和计算关税。</p><h2>必填字段</h2><ul><li><strong>发件人信息</strong>：姓名、地址、联系方式</li><li><strong>收件人信息</strong>：姓名、地址、联系方式</li><li><strong>发票日期和编号</strong></li><li><strong>商品描述</strong>：品名、材质、用途</li><li><strong>HS 编码</strong>：海关编码（建议使用 <a href="/tools/hs-code">HS编码查询工具</a>）</li><li><strong>数量和单位</strong></li><li><strong>单价和总价</strong>：币种和金额</li><li><strong>原产国</strong></li><li><strong>贸易条款</strong>（Incoterms）</li><li><strong>总重量和包装方式</strong></li></ul><h2>常见错误</h2><table class="guide-table"><tr><td>错误</td><td>后果</td></tr><tr><td>品名过于笼统（如"衣服"）</td><td>海关可能扣关查验</td></tr><tr><td>低报价值</td><td>罚款或没收</td></tr><tr><td>缺少 HS 编码</td><td>清关延迟</td></tr><tr><td>金额不一致</td><td>海关质疑</td></tr></table><h2>填写建议</h2><ul><li>品名要具体：不要写"衣服"，写"100% cotton t-shirt"</li><li>如实申报价值</li><li>使用正确的 HS 编码</li><li>保留发票副本</li></ul><blockquote>⚠️ 免责声明：以上信息仅供参考，具体报关要求请咨询专业报关行或海关官方。</blockquote><h2>相关工具</h2><ul><li><a href="/tools/commercial-invoice">发票生成器</a> — 在线生成商业发票</li><li><a href="/tools/handover-note">装箱单生成</a> — 生成配套装箱单</li><li><a href="/tools/hs-code">HS编码查询</a> — 查找正确编码</li></ul><h2>相关指南</h2><ul><li><a href="/guides/shipping-from-china-to-canada-guide">中国寄加拿大完整流程</a></li><li><a href="/guides/canada-address-format">加拿大地址和邮编格式</a></li><li><a href="/guides/packing-list-guide">装箱单填写指南</a></li></ul><h2>相关清单</h2><ul><li><a href="/checklists/export-documents-checklist">发货前资料检查清单</a></li><li><a href="/checklists/canada-shipping-checklist">中国寄加拿大 8 步清单</a></li></ul>' WHERE slug = 'commercial-invoice-guide';
UPDATE guides SET body = '<h2>什么是装箱单</h2><p>装箱单（Packing List）是详细列明每个包装内商品信息的单据，与商业发票配合使用。</p><h2>装箱单 vs 商业发票</h2><table class="guide-table"><tr><td>项目</td><td>商业发票</td><td>装箱单</td></tr><tr><td>核心信息</td><td>价值、贸易条款</td><td>数量、重量、包装</td></tr><tr><td>用途</td><td>报关、征税</td><td>验货、仓储</td></tr><tr><td>必须有价格</td><td>是</td><td>否</td></tr></table><h2>必填字段</h2><ul><li><strong>发件人/收件人信息</strong></li><li><strong>箱号</strong>：Carton No. 1/3, 2/3, 3/3</li><li><strong>每箱内容</strong>：品名、数量</li><li><strong>毛重（Gross Weight）</strong>：每箱 + 总计</li><li><strong>净重（Net Weight）</strong>：每箱 + 总计</li><li><strong>箱规</strong>：长×宽×高（建议使用 <a href="/tools/shipping-calculator">CBM计算器</a>）</li><li><strong>总体积（CBM）</strong></li></ul><h2>填写建议</h2><ul><li>每箱编号清晰</li><li>毛重净重要准确</li><li>箱规用厘米标注</li><li>总数量和总重量要与发票一致</li></ul><blockquote>⚠️ 免责声明：以上信息仅供参考，具体要求请咨询物流公司或海关官方。</blockquote><h2>相关工具</h2><ul><li><a href="/tools/handover-note">装箱单生成</a> — 在线生成装箱单</li><li><a href="/tools/shipping-calculator">CBM计算器</a> — 计算体积重</li><li><a href="/tools/commercial-invoice">发票生成器</a> — 配套发票</li></ul><h2>相关指南</h2><ul><li><a href="/guides/commercial-invoice-guide">商业发票填写指南</a></li><li><a href="/guides/shipping-from-china-to-canada-guide">中国寄加拿大完整流程</a></li></ul><h2>相关清单</h2><ul><li><a href="/checklists/export-documents-checklist">发货前资料检查清单</a></li></ul>' WHERE slug = 'packing-list-guide';
