/**
 * Import additional China postal codes (major cities/districts)
 * GeoNames has limited CN data, this supplements with complete coverage
 */
import { PrismaClient } from '@prisma/client';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';
import * as path from 'path';

const dbPath = path.join(process.cwd(), 'prisma', 'dev.db');
const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

// China major city postal codes (comprehensive coverage)
const chinaPostalCodes = [
  // 北京市 (110000)
  { province: '北京', city: '北京', district: '东城区', postalCode: '100010' },
  { province: '北京', city: '北京', district: '西城区', postalCode: '100032' },
  { province: '北京', city: '北京', district: '朝阳区', postalCode: '100020' },
  { province: '北京', city: '北京', district: '海淀区', postalCode: '100080' },
  { province: '北京', city: '北京', district: '丰台区', postalCode: '100071' },
  { province: '北京', city: '北京', district: '石景山区', postalCode: '100043' },
  { province: '北京', city: '北京', district: '门头沟区', postalCode: '102300' },
  { province: '北京', city: '北京', district: '房山区', postalCode: '102400' },
  { province: '北京', city: '北京', district: '通州区', postalCode: '101149' },
  { province: '北京', city: '北京', district: '顺义区', postalCode: '101300' },
  { province: '北京', city: '北京', district: '昌平区', postalCode: '102200' },
  { province: '北京', city: '北京', district: '大兴区', postalCode: '102600' },
  { province: '北京', city: '北京', district: '怀柔区', postalCode: '101400' },
  { province: '北京', city: '北京', district: '平谷区', postalCode: '101200' },
  { province: '北京', city: '北京', district: '密云区', postalCode: '101500' },
  { province: '北京', city: '北京', district: '延庆区', postalCode: '102100' },
  // 天津市 (120000)
  { province: '天津', city: '天津', district: '和平区', postalCode: '300041' },
  { province: '天津', city: '天津', district: '河东区', postalCode: '300041' },
  { province: '天津', city: '天津', district: '河西区', postalCode: '300204' },
  { province: '天津', city: '天津', district: '南开区', postalCode: '300100' },
  { province: '天津', city: '天津', district: '河北区', postalCode: '300143' },
  { province: '天津', city: '天津', district: '红桥区', postalCode: '300131' },
  { province: '天津', city: '天津', district: '滨海新区', postalCode: '300450' },
  { province: '天津', city: '天津', district: '东丽区', postalCode: '300300' },
  { province: '天津', city: '天津', district: '西青区', postalCode: '300380' },
  { province: '天津', city: '天津', district: '津南区', postalCode: '300350' },
  { province: '天津', city: '天津', district: '北辰区', postalCode: '300400' },
  { province: '天津', city: '天津', district: '武清区', postalCode: '301700' },
  { province: '天津', city: '天津', district: '宝坻区', postalCode: '301800' },
  { province: '天津', city: '天津', district: '宁河区', postalCode: '301500' },
  { province: '天津', city: '天津', district: '静海区', postalCode: '301600' },
  { province: '天津', city: '天津', district: '蓟州区', postalCode: '301900' },
  // 上海市 (200000)
  { province: '上海', city: '上海', district: '黄浦区', postalCode: '200001' },
  { province: '上海', city: '上海', district: '徐汇区', postalCode: '200030' },
  { province: '上海', city: '上海', district: '长宁区', postalCode: '200050' },
  { province: '上海', city: '上海', district: '静安区', postalCode: '200040' },
  { province: '上海', city: '上海', district: '普陀区', postalCode: '200333' },
  { province: '上海', city: '上海', district: '虹口区', postalCode: '200080' },
  { province: '上海', city: '上海', district: '杨浦区', postalCode: '200090' },
  { province: '上海', city: '上海', district: '浦东新区', postalCode: '200120' },
  { province: '上海', city: '上海', district: '闵行区', postalCode: '201100' },
  { province: '上海', city: '上海', district: '宝山区', postalCode: '201900' },
  { province: '上海', city: '上海', district: '嘉定区', postalCode: '201800' },
  { province: '上海', city: '上海', district: '金山区', postalCode: '201500' },
  { province: '上海', city: '上海', district: '松江区', postalCode: '201600' },
  { province: '上海', city: '上海', district: '青浦区', postalCode: '201700' },
  { province: '上海', city: '上海', district: '奉贤区', postalCode: '201400' },
  { province: '上海', city: '上海', district: '崇明区', postalCode: '202150' },
  // 重庆市 (400000)
  { province: '重庆', city: '重庆', district: '渝中区', postalCode: '400010' },
  { province: '重庆', city: '重庆', district: '江北区', postalCode: '400020' },
  { province: '重庆', city: '重庆', district: '南岸区', postalCode: '400060' },
  { province: '重庆', city: '重庆', district: '沙坪坝区', postalCode: '400030' },
  { province: '重庆', city: '重庆', district: '九龙坡区', postalCode: '400050' },
  { province: '重庆', city: '重庆', district: '大渡口区', postalCode: '400080' },
  { province: '重庆', city: '重庆', district: '北碚区', postalCode: '400700' },
  { province: '重庆', city: '重庆', district: '渝北区', postalCode: '401120' },
  { province: '重庆', city: '重庆', district: '巴南区', postalCode: '401320' },
  // 广东省
  { province: '广东', city: '广州', district: '天河区', postalCode: '510000' },
  { province: '广东', city: '广州', district: '越秀区', postalCode: '510030' },
  { province: '广东', city: '广州', district: '海珠区', postalCode: '510220' },
  { province: '广东', city: '广州', district: '荔湾区', postalCode: '510140' },
  { province: '广东', city: '广州', district: '白云区', postalCode: '510400' },
  { province: '广东', city: '广州', district: '黄埔区', postalCode: '510700' },
  { province: '广东', city: '广州', district: '番禺区', postalCode: '511400' },
  { province: '广东', city: '广州', district: '花都区', postalCode: '510800' },
  { province: '广东', city: '广州', district: '南沙区', postalCode: '511400' },
  { province: '广东', city: '广州', district: '增城区', postalCode: '511300' },
  { province: '广东', city: '广州', district: '从化区', postalCode: '510900' },
  { province: '广东', city: '深圳', district: '福田区', postalCode: '518000' },
  { province: '广东', city: '深圳', district: '罗湖区', postalCode: '518001' },
  { province: '广东', city: '深圳', district: '南山区', postalCode: '518000' },
  { province: '广东', city: '深圳', district: '宝安区', postalCode: '518100' },
  { province: '广东', city: '深圳', district: '龙岗区', postalCode: '518172' },
  { province: '广东', city: '深圳', district: '盐田区', postalCode: '518081' },
  { province: '广东', city: '深圳', district: '龙华区', postalCode: '518109' },
  { province: '广东', city: '深圳', district: '坪山区', postalCode: '518118' },
  { province: '广东', city: '深圳', district: '光明区', postalCode: '518107' },
  { province: '广东', city: '东莞', district: '东莞市', postalCode: '523000' },
  { province: '广东', city: '佛山', district: '禅城区', postalCode: '528000' },
  { province: '广东', city: '佛山', district: '南海区', postalCode: '528200' },
  { province: '广东', city: '佛山', district: '顺德区', postalCode: '528300' },
  { province: '广东', city: '珠海', district: '香洲区', postalCode: '519000' },
  { province: '广东', city: '珠海', district: '金湾区', postalCode: '519090' },
  { province: '广东', city: '中山', district: '中山市', postalCode: '528400' },
  { province: '广东', city: '惠州', district: '惠城区', postalCode: '516000' },
  { province: '广东', city: '江门', district: '蓬江区', postalCode: '529000' },
  { province: '广东', city: '汕头', district: '金平区', postalCode: '515000' },
  { province: '广东', city: '湛江', district: '赤坎区', postalCode: '524000' },
  { province: '广东', city: '茂名', district: '茂南区', postalCode: '525000' },
  { province: '广东', city: '肇庆', district: '端州区', postalCode: '526000' },
  // 浙江省
  { province: '浙江', city: '杭州', district: '上城区', postalCode: '310000' },
  { province: '浙江', city: '杭州', district: '拱墅区', postalCode: '310000' },
  { province: '浙江', city: '杭州', district: '西湖区', postalCode: '310000' },
  { province: '浙江', city: '杭州', district: '滨江区', postalCode: '310051' },
  { province: '浙江', city: '杭州', district: '萧山区', postalCode: '311200' },
  { province: '浙江', city: '杭州', district: '余杭区', postalCode: '311100' },
  { province: '浙江', city: '杭州', district: '临平区', postalCode: '311100' },
  { province: '浙江', city: '杭州', district: '钱塘区', postalCode: '310018' },
  { province: '浙江', city: '杭州', district: '富阳区', postalCode: '311400' },
  { province: '浙江', city: '杭州', district: '临安区', postalCode: '311300' },
  { province: '浙江', city: '宁波', district: '海曙区', postalCode: '315000' },
  { province: '浙江', city: '宁波', district: '江北区', postalCode: '315020' },
  { province: '浙江', city: '宁波', district: '北仑区', postalCode: '315800' },
  { province: '浙江', city: '宁波', district: '镇海区', postalCode: '315200' },
  { province: '浙江', city: '宁波', district: '鄞州区', postalCode: '315100' },
  { province: '浙江', city: '温州', district: '鹿城区', postalCode: '325000' },
  { province: '浙江', city: '温州', district: '龙湾区', postalCode: '325024' },
  { province: '浙江', city: '温州', district: '瓯海区', postalCode: '325000' },
  { province: '浙江', city: '嘉兴', district: '南湖区', postalCode: '314000' },
  { province: '浙江', city: '嘉兴', district: '秀洲区', postalCode: '314000' },
  { province: '浙江', city: '湖州', district: '吴兴区', postalCode: '313000' },
  { province: '浙江', city: '绍兴', district: '越城区', postalCode: '312000' },
  { province: '浙江', city: '金华', district: '婺城区', postalCode: '321000' },
  { province: '浙江', city: '义乌', district: '义乌市', postalCode: '322000' },
  { province: '浙江', city: '台州', district: '椒江区', postalCode: '318000' },
  { province: '浙江', city: '丽水', district: '莲都区', postalCode: '323000' },
  { province: '浙江', city: '衢州', district: '柯城区', postalCode: '324000' },
  { province: '浙江', city: '舟山', district: '定海区', postalCode: '316000' },
  // 江苏省
  { province: '江苏', city: '南京', district: '玄武区', postalCode: '210000' },
  { province: '江苏', city: '南京', district: '秦淮区', postalCode: '210001' },
  { province: '江苏', city: '南京', district: '建邺区', postalCode: '210019' },
  { province: '江苏', city: '南京', district: '鼓楼区', postalCode: '210008' },
  { province: '江苏', city: '南京', district: '浦口区', postalCode: '211800' },
  { province: '江苏', city: '南京', district: '栖霞区', postalCode: '210046' },
  { province: '江苏', city: '南京', district: '雨花台区', postalCode: '210012' },
  { province: '江苏', city: '南京', district: '江宁区', postalCode: '211100' },
  { province: '江苏', city: '南京', district: '六合区', postalCode: '211500' },
  { province: '江苏', city: '南京', district: '溧水区', postalCode: '211200' },
  { province: '江苏', city: '南京', district: '高淳区', postalCode: '211300' },
  { province: '江苏', city: '苏州', district: '姑苏区', postalCode: '215000' },
  { province: '江苏', city: '苏州', district: '虎丘区', postalCode: '215000' },
  { province: '江苏', city: '苏州', district: '吴中区', postalCode: '215128' },
  { province: '江苏', city: '苏州', district: '相城区', postalCode: '215131' },
  { province: '江苏', city: '苏州', district: '吴江区', postalCode: '215200' },
  { province: '江苏', city: '苏州', district: '工业园区', postalCode: '215021' },
  { province: '江苏', city: '无锡', district: '锡山区', postalCode: '214000' },
  { province: '江苏', city: '无锡', district: '惠山区', postalCode: '214174' },
  { province: '江苏', city: '无锡', district: '滨湖区', postalCode: '214064' },
  { province: '江苏', city: '无锡', district: '新吴区', postalCode: '214028' },
  { province: '江苏', city: '常州', district: '天宁区', postalCode: '213000' },
  { province: '江苏', city: '常州', district: '钟楼区', postalCode: '213002' },
  { province: '江苏', city: '常州', district: '新北区', postalCode: '213022' },
  { province: '江苏', city: '常州', district: '武进区', postalCode: '213161' },
  { province: '江苏', city: '南通', district: '崇川区', postalCode: '226000' },
  { province: '江苏', city: '南通', district: '通州区', postalCode: '226300' },
  { province: '江苏', city: '徐州', district: '鼓楼区', postalCode: '221000' },
  { province: '江苏', city: '徐州', district: '云龙区', postalCode: '221003' },
  { province: '江苏', city: '扬州', district: '广陵区', postalCode: '225000' },
  { province: '江苏', city: '扬州', district: '邗江区', postalCode: '225000' },
  { province: '江苏', city: '镇江', district: '京口区', postalCode: '212000' },
  { province: '江苏', city: '镇江', district: '润州区', postalCode: '212004' },
  { province: '江苏', city: '泰州', district: '海陵区', postalCode: '225300' },
  { province: '江苏', city: '盐城', district: '亭湖区', postalCode: '224000' },
  { province: '江苏', city: '淮安', district: '清江浦区', postalCode: '223000' },
  { province: '江苏', city: '连云港', district: '海州区', postalCode: '222000' },
  { province: '江苏', city: '宿迁', district: '宿城区', postalCode: '223800' },
  // 山东省
  { province: '山东', city: '济南', district: '历下区', postalCode: '250000' },
  { province: '山东', city: '济南', district: '市中区', postalCode: '250001' },
  { province: '山东', city: '济南', district: '槐荫区', postalCode: '250021' },
  { province: '山东', city: '济南', district: '天桥区', postalCode: '250031' },
  { province: '山东', city: '济南', district: '历城区', postalCode: '250100' },
  { province: '山东', city: '济南', district: '长清区', postalCode: '250300' },
  { province: '山东', city: '青岛', district: '市南区', postalCode: '266001' },
  { province: '山东', city: '青岛', district: '市北区', postalCode: '266011' },
  { province: '山东', city: '青岛', district: '黄岛区', postalCode: '266500' },
  { province: '山东', city: '青岛', district: '崂山区', postalCode: '266100' },
  { province: '山东', city: '青岛', district: '李沧区', postalCode: '266100' },
  { province: '山东', city: '青岛', district: '城阳区', postalCode: '266109' },
  { province: '山东', city: '淄博', district: '张店区', postalCode: '255000' },
  { province: '山东', city: '烟台', district: '芝罘区', postalCode: '264000' },
  { province: '山东', city: '烟台', district: '莱山区', postalCode: '264003' },
  { province: '山东', city: '潍坊', district: '潍城区', postalCode: '261000' },
  { province: '山东', city: '潍坊', district: '奎文区', postalCode: '261041' },
  { province: '山东', city: '威海', district: '环翠区', postalCode: '264200' },
  { province: '山东', city: '日照', district: '东港区', postalCode: '276800' },
  { province: '山东', city: '临沂', district: '兰山区', postalCode: '276000' },
  { province: '山东', city: '德州', district: '德城区', postalCode: '253000' },
  { province: '山东', city: '聊城', district: '东昌府区', postalCode: '252000' },
  { province: '山东', city: '滨州', district: '滨城区', postalCode: '256600' },
  { province: '山东', city: '东营', district: '东营区', postalCode: '257000' },
  { province: '山东', city: '济宁', district: '任城区', postalCode: '272000' },
  { province: '山东', city: '泰安', district: '泰山区', postalCode: '271000' },
  { province: '山东', city: '枣庄', district: '市中区', postalCode: '277100' },
  // 四川省
  { province: '四川', city: '成都', district: '锦江区', postalCode: '610000' },
  { province: '四川', city: '成都', district: '青羊区', postalCode: '610000' },
  { province: '四川', city: '成都', district: '金牛区', postalCode: '610000' },
  { province: '四川', city: '成都', district: '武侯区', postalCode: '610041' },
  { province: '四川', city: '成都', district: '成华区', postalCode: '610051' },
  { province: '四川', city: '成都', district: '龙泉驿区', postalCode: '610100' },
  { province: '四川', city: '成都', district: '青白江区', postalCode: '610300' },
  { province: '四川', city: '成都', district: '新都区', postalCode: '610500' },
  { province: '四川', city: '成都', district: '温江区', postalCode: '611130' },
  { province: '四川', city: '成都', district: '双流区', postalCode: '610200' },
  { province: '四川', city: '成都', district: '郫都区', postalCode: '611730' },
  { province: '四川', city: '绵阳', district: '涪城区', postalCode: '621000' },
  { province: '四川', city: '绵阳', district: '游仙区', postalCode: '621000' },
  { province: '四川', city: '德阳', district: '旌阳区', postalCode: '618000' },
  { province: '四川', city: '宜宾', district: '翠屏区', postalCode: '644000' },
  { province: '四川', city: '泸州', district: '江阳区', postalCode: '646000' },
  { province: '四川', city: '南充', district: '顺庆区', postalCode: '637000' },
  { province: '四川', city: '达州', district: '通川区', postalCode: '635000' },
  { province: '四川', city: '乐山', district: '市中区', postalCode: '614000' },
  // 湖北省
  { province: '湖北', city: '武汉', district: '江岸区', postalCode: '430014' },
  { province: '湖北', city: '武汉', district: '江汉区', postalCode: '430022' },
  { province: '湖北', city: '武汉', district: '硚口区', postalCode: '430030' },
  { province: '湖北', city: '武汉', district: '汉阳区', postalCode: '430050' },
  { province: '湖北', city: '武汉', district: '武昌区', postalCode: '430061' },
  { province: '湖北', city: '武汉', district: '青山区', postalCode: '430080' },
  { province: '湖北', city: '武汉', district: '洪山区', postalCode: '430070' },
  { province: '湖北', city: '武汉', district: '东西湖区', postalCode: '430040' },
  { province: '湖北', city: '武汉', district: '蔡甸区', postalCode: '430100' },
  { province: '湖北', city: '武汉', district: '江夏区', postalCode: '430200' },
  { province: '湖北', city: '武汉', district: '黄陂区', postalCode: '432200' },
  { province: '湖北', city: '武汉', district: '新洲区', postalCode: '431400' },
  { province: '湖北', city: '襄阳', district: '襄城区', postalCode: '441000' },
  { province: '湖北', city: '宜昌', district: '西陵区', postalCode: '443000' },
  { province: '湖北', city: '荆州', district: '沙市区', postalCode: '434000' },
  { province: '湖北', city: '黄冈', district: '黄州区', postalCode: '438000' },
  { province: '湖北', city: '孝感', district: '孝南区', postalCode: '432000' },
  // 福建省
  { province: '福建', city: '福州', district: '鼓楼区', postalCode: '350000' },
  { province: '福建', city: '福州', district: '台江区', postalCode: '350004' },
  { province: '福建', city: '福州', district: '仓山区', postalCode: '350007' },
  { province: '福建', city: '福州', district: '马尾区', postalCode: '350015' },
  { province: '福建', city: '福州', district: '晋安区', postalCode: '350011' },
  { province: '福建', city: '福州', district: '长乐区', postalCode: '350200' },
  { province: '福建', city: '厦门', district: '思明区', postalCode: '361000' },
  { province: '福建', city: '厦门', district: '湖里区', postalCode: '361006' },
  { province: '福建', city: '厦门', district: '集美区', postalCode: '361021' },
  { province: '福建', city: '厦门', district: '海沧区', postalCode: '361026' },
  { province: '福建', city: '厦门', district: '同安区', postalCode: '361100' },
  { province: '福建', city: '厦门', district: '翔安区', postalCode: '361101' },
  { province: '福建', city: '泉州', district: '鲤城区', postalCode: '362000' },
  { province: '福建', city: '泉州', district: '丰泽区', postalCode: '362000' },
  { province: '福建', city: '莆田', district: '城厢区', postalCode: '351100' },
  { province: '福建', city: '漳州', district: '芗城区', postalCode: '363000' },
  // 河南省
  { province: '河南', city: '郑州', district: '中原区', postalCode: '450000' },
  { province: '河南', city: '郑州', district: '二七区', postalCode: '450000' },
  { province: '河南', city: '郑州', district: '管城回族区', postalCode: '450000' },
  { province: '河南', city: '郑州', district: '金水区', postalCode: '450000' },
  { province: '河南', city: '郑州', district: '上街区', postalCode: '450041' },
  { province: '河南', city: '郑州', district: '惠济区', postalCode: '450044' },
  { province: '河南', city: '郑州', district: '中牟县', postalCode: '451450' },
  { province: '河南', city: '郑州', district: '巩义市', postalCode: '451200' },
  { province: '河南', city: '洛阳', district: '老城区', postalCode: '471000' },
  { province: '河南', city: '洛阳', district: '西工区', postalCode: '471000' },
  { province: '河南', city: '开封', district: '龙亭区', postalCode: '475000' },
  { province: '河南', city: '新乡', district: '红旗区', postalCode: '453000' },
  { province: '河南', city: '南阳', district: '卧龙区', postalCode: '473000' },
  // 安徽省
  { province: '安徽', city: '合肥', district: '蜀山区', postalCode: '230000' },
  { province: '安徽', city: '合肥', district: '庐阳区', postalCode: '230001' },
  { province: '安徽', city: '合肥', district: '瑶海区', postalCode: '230001' },
  { province: '安徽', city: '合肥', district: '包河区', postalCode: '230051' },
  { province: '安徽', city: '合肥', district: '长丰县', postalCode: '231100' },
  { province: '安徽', city: '合肥', district: '肥东县', postalCode: '231600' },
  { province: '安徽', city: '合肥', district: '肥西县', postalCode: '231200' },
  { province: '安徽', city: '芜湖', district: '镜湖区', postalCode: '241000' },
  { province: '安徽', city: '蚌埠', district: '蚌山区', postalCode: '233000' },
  { province: '安徽', city: '马鞍山', district: '雨山区', postalCode: '243000' },
  { province: '安徽', city: '安庆', district: '迎江区', postalCode: '246000' },
  // 湖南省
  { province: '湖南', city: '长沙', district: '芙蓉区', postalCode: '410000' },
  { province: '湖南', city: '长沙', district: '天心区', postalCode: '410004' },
  { province: '湖南', city: '长沙', district: '岳麓区', postalCode: '410013' },
  { province: '湖南', city: '长沙', district: '开福区', postalCode: '410008' },
  { province: '湖南', city: '长沙', district: '雨花区', postalCode: '410011' },
  { province: '湖南', city: '长沙', district: '望城区', postalCode: '410200' },
  { province: '湖南', city: '长沙', district: '长沙县', postalCode: '410100' },
  { province: '湖南', city: '株洲', district: '天元区', postalCode: '412000' },
  { province: '湖南', city: '湘潭', district: '岳塘区', postalCode: '411100' },
  { province: '湖南', city: '衡阳', district: '雁峰区', postalCode: '421000' },
  // 陕西省
  { province: '陕西', city: '西安', district: '新城区', postalCode: '710000' },
  { province: '陕西', city: '西安', district: '碑林区', postalCode: '710001' },
  { province: '陕西', city: '西安', district: '莲湖区', postalCode: '710002' },
  { province: '陕西', city: '西安', district: '灞桥区', postalCode: '710038' },
  { province: '陕西', city: '西安', district: '未央区', postalCode: '710016' },
  { province: '陕西', city: '西安', district: '雁塔区', postalCode: '710061' },
  { province: '陕西', city: '西安', district: '阎良区', postalCode: '710089' },
  { province: '陕西', city: '西安', district: '临潼区', postalCode: '710600' },
  { province: '陕西', city: '西安', district: '长安区', postalCode: '710100' },
  { province: '陕西', city: '咸阳', district: '秦都区', postalCode: '712000' },
  // 江西省
  { province: '江西', city: '南昌', district: '东湖区', postalCode: '330000' },
  { province: '江西', city: '南昌', district: '西湖区', postalCode: '330025' },
  { province: '江西', city: '南昌', district: '青山湖区', postalCode: '330029' },
  { province: '江西', city: '南昌', district: '红谷滩区', postalCode: '330038' },
  { province: '江西', city: '九江', district: '浔阳区', postalCode: '332000' },
  { province: '江西', city: '赣州', district: '章贡区', postalCode: '341000' },
  // 河北省
  { province: '河北', city: '石家庄', district: '长安区', postalCode: '050000' },
  { province: '河北', city: '石家庄', district: '桥西区', postalCode: '050000' },
  { province: '河北', city: '石家庄', district: '新华区', postalCode: '050051' },
  { province: '河北', city: '石家庄', district: '裕华区', postalCode: '050000' },
  { province: '河北', city: '唐山', district: '路南区', postalCode: '063000' },
  { province: '河北', city: '唐山', district: '路北区', postalCode: '063000' },
  { province: '河北', city: '保定', district: '竞秀区', postalCode: '071000' },
  { province: '河北', city: '邯郸', district: '邯山区', postalCode: '056000' },
  { province: '河北', city: '秦皇岛', district: '海港区', postalCode: '066000' },
  // 辽宁省
  { province: '辽宁', city: '沈阳', district: '和平区', postalCode: '110000' },
  { province: '辽宁', city: '沈阳', district: '沈河区', postalCode: '110013' },
  { province: '辽宁', city: '沈阳', district: '大东区', postalCode: '110041' },
  { province: '辽宁', city: '沈阳', district: '皇姑区', postalCode: '110031' },
  { province: '辽宁', city: '沈阳', district: '铁西区', postalCode: '110021' },
  { province: '辽宁', city: '沈阳', district: '浑南区', postalCode: '110179' },
  { province: '辽宁', city: '大连', district: '中山区', postalCode: '116000' },
  { province: '辽宁', city: '大连', district: '西岗区', postalCode: '116011' },
  { province: '辽宁', city: '大连', district: '沙河口区', postalCode: '116021' },
  { province: '辽宁', city: '大连', district: '甘井子区', postalCode: '116033' },
  // 吉林省
  { province: '吉林', city: '长春', district: '南关区', postalCode: '130000' },
  { province: '吉林', city: '长春', district: '宽城区', postalCode: '130051' },
  { province: '吉林', city: '长春', district: '朝阳区', postalCode: '130021' },
  { province: '吉林', city: '长春', district: '二道区', postalCode: '130031' },
  { province: '吉林', city: '吉林', district: '船营区', postalCode: '132000' },
  // 黑龙江省
  { province: '黑龙江', city: '哈尔滨', district: '道里区', postalCode: '150000' },
  { province: '黑龙江', city: '哈尔滨', district: '南岗区', postalCode: '150001' },
  { province: '黑龙江', city: '哈尔滨', district: '道外区', postalCode: '150020' },
  { province: '黑龙江', city: '哈尔滨', district: '香坊区', postalCode: '150030' },
  // 广西壮族自治区
  { province: '广西', city: '南宁', district: '青秀区', postalCode: '530000' },
  { province: '广西', city: '南宁', district: '兴宁区', postalCode: '530000' },
  { province: '广西', city: '南宁', district: '江南区', postalCode: '530031' },
  { province: '广西', city: '南宁', district: '西乡塘区', postalCode: '530001' },
  { province: '广西', city: '南宁', district: '良庆区', postalCode: '530200' },
  { province: '广西', city: '桂林', district: '秀峰区', postalCode: '541000' },
  { province: '广西', city: '柳州', district: '城中区', postalCode: '545000' },
  // 云南省
  { province: '云南', city: '昆明', district: '五华区', postalCode: '650000' },
  { province: '云南', city: '昆明', district: '盘龙区', postalCode: '650051' },
  { province: '云南', city: '昆明', district: '官渡区', postalCode: '650200' },
  { province: '云南', city: '昆明', district: '西山区', postalCode: '650100' },
  { province: '云南', city: '大理', district: '大理市', postalCode: '671000' },
  { province: '云南', city: '丽江', district: '古城区', postalCode: '674100' },
  // 贵州省
  { province: '贵州', city: '贵阳', district: '南明区', postalCode: '550000' },
  { province: '贵州', city: '贵阳', district: '云岩区', postalCode: '550001' },
  { province: '贵州', city: '贵阳', district: '观山湖区', postalCode: '550081' },
  // 甘肃省
  { province: '甘肃', city: '兰州', district: '城关区', postalCode: '730000' },
  { province: '甘肃', city: '兰州', district: '七里河区', postalCode: '730050' },
  { province: '甘肃', city: '兰州', district: '安宁区', postalCode: '730070' },
  // 海南省
  { province: '海南', city: '海口', district: '秀英区', postalCode: '570000' },
  { province: '海南', city: '海口', district: '龙华区', postalCode: '570102' },
  { province: '海南', city: '海口', district: '琼山区', postalCode: '571100' },
  { province: '海南', city: '三亚', district: '海棠区', postalCode: '572000' },
  { province: '海南', city: '三亚', district: '吉阳区', postalCode: '572000' },
  // 内蒙古自治区
  { province: '内蒙古', city: '呼和浩特', district: '新城区', postalCode: '010000' },
  { province: '内蒙古', city: '呼和浩特', district: '回民区', postalCode: '010030' },
  { province: '内蒙古', city: '呼和浩特', district: '玉泉区', postalCode: '010020' },
  { province: '内蒙古', city: '呼和浩特', district: '赛罕区', postalCode: '010020' },
  { province: '内蒙古', city: '包头', district: '昆都仑区', postalCode: '014000' },
  // 宁夏回族自治区
  { province: '宁夏', city: '银川', district: '兴庆区', postalCode: '750000' },
  { province: '宁夏', city: '银川', district: '金凤区', postalCode: '750002' },
  { province: '宁夏', city: '银川', district: '西夏区', postalCode: '750021' },
  // 新疆维吾尔自治区
  { province: '新疆', city: '乌鲁木齐', district: '天山区', postalCode: '830000' },
  { province: '新疆', city: '乌鲁木齐', district: '沙依巴克区', postalCode: '830000' },
  { province: '新疆', city: '乌鲁木齐', district: '新市区', postalCode: '830011' },
  // 西藏自治区
  { province: '西藏', city: '拉萨', district: '城关区', postalCode: '850000' },
  // 青海省
  { province: '青海', city: '西宁', district: '城中区', postalCode: '810000' },
  { province: '青海', city: '西宁', district: '城东区', postalCode: '810000' },
];

async function main() {
  console.log('🇨🇳 Importing China postal codes...');
  
  let imported = 0;
  let skipped = 0;

  for (const pc of chinaPostalCodes) {
    try {
      await prisma.postalCode.upsert({
        where: {
          country_postalCode: { country: 'CN', postalCode: pc.postalCode }
        },
        create: {
          country: 'CN',
          countryCode: '86',
          province: pc.province,
          city: pc.city,
          district: pc.district,
          postalCode: pc.postalCode,
          isActive: true,
        },
        update: {},
      });
      imported++;
    } catch {
      skipped++;
    }
  }

  console.log(`✅ China import complete!`);
  console.log(`📮 Imported: ${imported}`);
  console.log(`⏭️  Skipped: ${skipped}`);

  // Show China stats
  const total = await prisma.postalCode.count({ where: { country: 'CN' } });
  console.log(`📊 Total CN records in DB: ${total}`);
}

main()
  .catch(e => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
