// 新手资源种子数据
// 用于导入数据库的 starter 分类资源

export const starterSeedResources = [
  // 外网新手必装软件
  {
    name: 'Chrome 浏览器',
    url: 'https://www.google.com/chrome/',
    description: '全球最流行的浏览器，扩展生态丰富',
    category: 'starter',
    tags: ['浏览器', '必装', '新手必看'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Bitwarden 密码管理器',
    url: 'https://bitwarden.com/',
    description: '免费开源的密码管理工具，保护账号安全',
    category: 'starter',
    tags: ['密码管理', '安全', '必装'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Google 翻译',
    url: 'https://translate.google.com/',
    description: '支持 100+ 语言的即时翻译工具',
    category: 'starter',
    tags: ['翻译', '语言', '效率'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'uBlock Origin',
    url: 'https://ublockorigin.com/',
    description: '轻量高效的广告拦截浏览器扩展',
    category: 'starter',
    tags: ['广告拦截', '隐私', '扩展'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Google Drive',
    url: 'https://drive.google.com/',
    description: '15GB 免费云存储，文档协作必备',
    category: 'starter',
    tags: ['云存储', '协作', '文档'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Signal 加密通讯',
    url: 'https://signal.org/',
    description: '端到端加密的即时通讯应用',
    category: 'starter',
    tags: ['通讯', '隐私', '安全'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 6,
  },

  // AI 工具
  {
    name: 'ChatGPT',
    url: 'https://chat.openai.com/',
    description: 'OpenAI 推出的 AI 对话助手',
    category: 'ai-tools',
    tags: ['AI', '对话', '写作'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Claude',
    url: 'https://claude.ai/',
    description: 'Anthropic 开发的 AI 助手，擅长长文本分析',
    category: 'ai-tools',
    tags: ['AI', '分析', '写作'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Midjourney',
    url: 'https://www.midjourney.com/',
    description: 'AI 图像生成工具，输入文字即可生成高质量图片',
    category: 'ai-tools',
    tags: ['AI', '图像', '创作'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Gemini',
    url: 'https://gemini.google.com/',
    description: 'Google 的 AI 助手，深度整合 Google 生态',
    category: 'ai-tools',
    tags: ['AI', 'Google', '多模态'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'GitHub Copilot',
    url: 'https://github.com/features/copilot',
    description: 'Microsoft 的 AI 编程助手',
    category: 'ai-tools',
    tags: ['AI', '编程', '开发'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 14,
  },

  // 视频与学习平台
  {
    name: 'YouTube',
    url: 'https://www.youtube.com/',
    description: '全球最大的视频分享平台',
    category: 'video-learning',
    tags: ['视频', '学习', '娱乐'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 20,
  },
  {
    name: 'Coursera',
    url: 'https://www.coursera.org/',
    description: '全球顶尖大学的在线课程平台',
    category: 'video-learning',
    tags: ['课程', '学习', '证书'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 21,
  },
  {
    name: 'Khan Academy',
    url: 'https://www.khanacademy.org/',
    description: '免费的在线教育平台，覆盖数学、科学等',
    category: 'video-learning',
    tags: ['免费', '教育', 'K12'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 22,
  },
  {
    name: 'edX',
    url: 'https://www.edx.org/',
    description: '哈佛 MIT 创办的在线学习平台',
    category: 'video-learning',
    tags: ['大学课程', '学习', '证书'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 23,
  },

  // 海外华人常用网站
  {
    name: 'Wise 跨境汇款',
    url: 'https://wise.com/',
    description: '低手续费的国际汇款服务',
    category: 'overseas-life',
    tags: ['汇款', '金融', '跨境'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 30,
  },
  {
    name: 'Amazon 全球购物',
    url: 'https://www.amazon.com/',
    description: '全球最大的电商平台',
    category: 'overseas-life',
    tags: ['购物', '电商', '生活'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 31,
  },
  {
    name: 'PayPal',
    url: 'https://www.paypal.com/',
    description: '全球通用的在线支付工具',
    category: 'overseas-life',
    tags: ['支付', '金融', '收款'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 32,
  },
  {
    name: 'X (Twitter)',
    url: 'https://x.com/',
    description: '全球信息社交平台',
    category: 'overseas-life',
    tags: ['社交', '资讯', '平台'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 33,
  },

  // 出海经营工具
  {
    name: 'Shopify',
    url: 'https://www.shopify.com/',
    description: '一站式跨境电商建站平台',
    category: 'business-tools',
    tags: ['建站', '电商', '跨境'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 40,
  },
  {
    name: 'Stripe',
    url: 'https://stripe.com/',
    description: '全球领先的在线支付处理商',
    category: 'business-tools',
    tags: ['支付', '收款', '金融'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 41,
  },
  {
    name: 'Cloudflare',
    url: 'https://www.cloudflare.com/',
    description: '全球 CDN 和网站安全服务',
    category: 'business-tools',
    tags: ['CDN', '安全', '基础设施'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 42,
  },
  {
    name: 'Google Analytics',
    url: 'https://analytics.google.com/',
    description: '网站流量分析工具',
    category: 'business-tools',
    tags: ['分析', '数据', '营销'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 43,
  },

  // 账号安全与隐私保护
  {
    name: 'Google Authenticator',
    url: 'https://support.google.com/accounts/answer/1066447',
    description: '两步验证应用，保护账号安全',
    category: 'security',
    tags: ['2FA', '安全', '认证'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 50,
  },
  {
    name: 'ProtonMail 加密邮箱',
    url: 'https://proton.me/mail',
    description: '瑞士端到端加密邮箱服务',
    category: 'security',
    tags: ['邮箱', '加密', '隐私'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 51,
  },
  {
    name: '1Password',
    url: 'https://1password.com/',
    description: '付费密码管理器，家庭共享方案',
    category: 'security',
    tags: ['密码', '管理', '安全'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 52,
  },
  {
    name: 'Privacy Badger',
    url: 'https://privacybadger.org/',
    description: 'EFF 开发的隐私保护浏览器扩展',
    category: 'security',
    tags: ['隐私', '防追踪', '扩展'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 53,
  },

  // 浏览器插件
  {
    name: 'DeepL 翻译',
    url: 'https://www.deepl.com/',
    description: '高质量 AI 翻译浏览器扩展',
    category: 'browser-extensions',
    tags: ['翻译', 'AI', '效率'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 60,
  },
  {
    name: 'Dark Reader',
    url: 'https://darkreader.org/',
    description: '为任意网站启用暗色模式',
    category: 'browser-extensions',
    tags: ['暗色', '护眼', '体验'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 61,
  },
  {
    name: 'Honey 比价',
    url: 'https://www.joinhoney.com/',
    description: '自动查找优惠券和比价',
    category: 'browser-extensions',
    tags: ['比价', '购物', '省钱'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 62,
  },
  {
    name: 'Notion Web Clipper',
    url: 'https://www.notion.so/web-clipper',
    description: '保存网页到 Notion 笔记',
    category: 'browser-extensions',
    tags: ['笔记', '收藏', '效率'],
    sourceType: 'third-party',
    isActive: true,
    sortOrder: 63,
  },
];
