'use client';

export interface AdItem {
  slotKey: string;
  type: 'text' | 'image' | 'banner' | 'card';
  enabled: boolean;
  title: string;
  subtitle?: string;
  description?: string;
  imageUrl?: string;
  href: string;
  ctaText?: string;
  tag?: string;
  advertiserName?: string;
  startAt?: string;
  endAt?: string;
  sortOrder: number;
  displayDevices: ('desktop' | 'tablet' | 'mobile')[];
  nofollow: boolean;
  sponsored: boolean;
  trackingKey?: string;
}

export interface AdGroup {
  groupKey: string;
  title: string;
  description?: string;
  position: string;
  enabled: boolean;
  showLabel: boolean;
  maxTextRows: number;
  textColumns: number;
  imageColumns: number;
  mobileMode: 'full' | 'compact' | 'hidden';
  sortOrder: number;
  textAds: AdItem[];
  imageAds: AdItem[];
}

export const mockAdInventory: AdGroup[] = [
  {
    groupKey: 'home_after_hero_ad_group',
    title: '首屏推荐广告位',
    description: 'Hero 区域下方的精选广告位',
    position: 'after_hero',
    enabled: true,
    showLabel: true,
    maxTextRows: 2,
    textColumns: 5,
    imageColumns: 4,
    mobileMode: 'compact',
    sortOrder: 10,
    textAds: [
      {
        slotKey: 'hero_text_01',
        type: 'text',
        enabled: true,
        title: '极速国际快递',
        subtitle: '中美专线 3-5天送达',
        description: '覆盖全球200+国家，支持实时追踪',
        href: 'https://example.com/ads/express-shipping',
        ctaText: '立即下单',
        tag: '热门',
        advertiserName: '环球速递',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_01_click',
      },
      {
        slotKey: 'hero_text_02',
        type: 'text',
        enabled: true,
        title: '海外留学规划',
        subtitle: '英美澳加名校申请',
        description: '一站式留学服务，成功率98%',
        href: 'https://example.com/ads/study-abroad',
        ctaText: '免费咨询',
        tag: '推荐',
        advertiserName: '启航留学',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_02_click',
      },
      {
        slotKey: 'hero_text_03',
        type: 'text',
        enabled: true,
        title: '跨境电商开店',
        subtitle: '亚马逊/Temu/SHEIN',
        description: '从0到1开店指导，月销百万不是梦',
        href: 'https://example.com/ads/ecommerce',
        ctaText: '了解详情',
        tag: '新手友好',
        advertiserName: '出海商学院',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_03_click',
      },
      {
        slotKey: 'hero_text_04',
        type: 'text',
        enabled: true,
        title: '境外银行账户',
        subtitle: '美国/新加坡/香港开户',
        description: '远程开户，无需出国，3天获批',
        href: 'https://example.com/ads/overseas-bank',
        ctaText: '预约开户',
        tag: '限时',
        advertiserName: '全球金融通',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_04_click',
      },
      {
        slotKey: 'hero_text_05',
        type: 'text',
        enabled: true,
        title: '海外医疗保险',
        subtitle: '覆盖全球就医费用',
        description: '最高保额100万美元，含新冠保障',
        href: 'https://example.com/ads/insurance',
        ctaText: '立即投保',
        advertiserName: '安心保',
        sortOrder: 5,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_05_click',
      },
      {
        slotKey: 'hero_text_06',
        type: 'text',
        enabled: true,
        title: '海外VPN加速',
        subtitle: '全球节点 稳定不限速',
        description: '企业级加密，7天无理由退款',
        href: 'https://example.com/ads/vpn',
        ctaText: '免费试用',
        tag: '特惠',
        advertiserName: '云速通',
        sortOrder: 6,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_06_click',
      },
      {
        slotKey: 'hero_text_07',
        type: 'text',
        enabled: false,
        title: '海外房产投资',
        subtitle: '日本/泰国/迪拜',
        description: '永久产权，年回报8%+',
        href: 'https://example.com/ads/property',
        ctaText: '查看详情',
        advertiserName: '环球置业',
        sortOrder: 7,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_07_click',
      },
      {
        slotKey: 'hero_text_08',
        type: 'text',
        enabled: true,
        title: '国际汇款转账',
        subtitle: '低费率 实时到账',
        description: '支持50+币种，手续费低至0.3%',
        href: 'https://example.com/ads/remittance',
        ctaText: '立即汇款',
        advertiserName: '速汇通',
        sortOrder: 8,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_08_click',
      },
      {
        slotKey: 'hero_text_09',
        type: 'text',
        enabled: true,
        title: '海外税务筹划',
        subtitle: '合法节税方案',
        description: 'CRS合规，专业CPA团队服务',
        href: 'https://example.com/ads/tax',
        ctaText: '预约咨询',
        advertiserName: '德信财税',
        sortOrder: 9,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_09_click',
      },
      {
        slotKey: 'hero_text_10',
        type: 'text',
        enabled: true,
        title: '海外华人社区',
        subtitle: '50万+海外华人聚集',
        description: '求职、租房、二手、交友一站式',
        href: 'https://example.com/ads/community',
        ctaText: '加入社区',
        tag: '免费',
        advertiserName: '华人之家',
        sortOrder: 10,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_text_10_click',
      },
    ],
    imageAds: [
      {
        slotKey: 'hero_img_01',
        type: 'image',
        enabled: true,
        title: '黑五物流大促',
        subtitle: '首重立减50%',
        imageUrl: '/images/ads/hero-black-friday-shipping.jpg',
        href: 'https://example.com/ads/black-friday-shipping',
        ctaText: '立即抢购',
        advertiserName: '速达国际',
        startAt: '2026-07-01',
        endAt: '2026-07-31',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_img_01_click',
      },
      {
        slotKey: 'hero_img_02',
        type: 'image',
        enabled: true,
        title: '留学季早鸟优惠',
        subtitle: '申请费全免',
        imageUrl: '/images/ads/hero-study-abroad-early-bird.jpg',
        href: 'https://example.com/ads/study-abroad-early-bird',
        ctaText: '立即申请',
        advertiserName: '启航留学',
        startAt: '2026-07-01',
        endAt: '2026-08-31',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_img_02_click',
      },
      {
        slotKey: 'hero_img_03',
        type: 'image',
        enabled: true,
        title: '跨境电商训练营',
        subtitle: '7天从零到出单',
        imageUrl: '/images/ads/hero-ecommerce-training.jpg',
        href: 'https://example.com/ads/ecommerce-training',
        ctaText: '免费报名',
        advertiserName: '出海商学院',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_img_03_click',
      },
      {
        slotKey: 'hero_img_04',
        type: 'image',
        enabled: false,
        title: '海外信用卡申请',
        subtitle: '年费减免 积分翻倍',
        imageUrl: '/images/ads/hero-credit-card.jpg',
        href: 'https://example.com/ads/credit-card',
        ctaText: '在线申请',
        advertiserName: '全球金融通',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'hero_img_04_click',
      },
    ],
  },
  {
    groupKey: 'home_after_tools_ad_group',
    title: '工具区下方广告位',
    description: '工具推荐区域下方的广告展示',
    position: 'after_tools',
    enabled: true,
    showLabel: true,
    maxTextRows: 4,
    textColumns: 5,
    imageColumns: 5,
    mobileMode: 'compact',
    sortOrder: 20,
    textAds: [
      {
        slotKey: 'tools_text_01',
        type: 'text',
        enabled: true,
        title: '集运仓储服务',
        subtitle: '中美/中英/中日专线',
        description: '免费仓储90天，合箱减重省运费',
        href: 'https://example.com/ads/warehousing',
        ctaText: '获取报价',
        tag: '省心',
        advertiserName: '海运达',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_01_click',
      },
      {
        slotKey: 'tools_text_02',
        type: 'text',
        enabled: true,
        title: '海外公司注册',
        subtitle: '美国/英国/新加坡/香港',
        description: '最快3天出证，含银行开户协助',
        href: 'https://example.com/ads/company-registration',
        ctaText: '免费咨询',
        advertiserName: '环球商务',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_02_click',
      },
      {
        slotKey: 'tools_text_03',
        type: 'text',
        enabled: true,
        title: '国际驾照翻译',
        subtitle: '196国通用 IDP办理',
        description: '在线申请，7个工作日寄达',
        href: 'https://example.com/ads/idp',
        ctaText: '立即办理',
        advertiserName: '出行无忧',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_03_click',
      },
      {
        slotKey: 'tools_text_04',
        type: 'text',
        enabled: true,
        title: '海外学历认证',
        subtitle: '教育部留服中心合作',
        description: '快速认证，不成功全额退款',
        href: 'https://example.com/ads/degree-cert',
        ctaText: '提交申请',
        advertiserName: '学信国际',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_04_click',
      },
      {
        slotKey: 'tools_text_05',
        type: 'text',
        enabled: true,
        title: '跨境支付收款',
        subtitle: '支持PayPal/Stripe/WT',
        description: '费率低至0.5%，T+0到账',
        href: 'https://example.com/ads/payment',
        ctaText: '开通账户',
        tag: '商家推荐',
        advertiserName: '汇付天下',
        sortOrder: 5,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_05_click',
      },
      {
        slotKey: 'tools_text_06',
        type: 'text',
        enabled: true,
        title: '海外电话卡',
        subtitle: '美/英/日/韩实体eSIM',
        description: '本地号码，流量不限量',
        href: 'https://example.com/ads/sim-card',
        ctaText: '在线购买',
        advertiserName: '环球通信',
        sortOrder: 6,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_06_click',
      },
      {
        slotKey: 'tools_text_07',
        type: 'text',
        enabled: true,
        title: '移民签证服务',
        subtitle: 'EB-1A/EB-5/投资移民',
        description: '资深律师团队，通过率95%',
        href: 'https://example.com/ads/immigration',
        ctaText: '评估资格',
        tag: '专业',
        advertiserName: '金桥移民',
        sortOrder: 7,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_07_click',
      },
      {
        slotKey: 'tools_text_08',
        type: 'text',
        enabled: false,
        title: '海外租车服务',
        subtitle: '全球200+城市',
        description: '中文导航，全险覆盖',
        href: 'https://example.com/ads/car-rental',
        ctaText: '立即预订',
        advertiserName: '自驾环球',
        sortOrder: 8,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_08_click',
      },
      {
        slotKey: 'tools_text_09',
        type: 'text',
        enabled: true,
        title: '国际物流追踪',
        subtitle: '一键查询所有包裹',
        description: '支持DHL/FedEx/UPS等100+快递',
        href: 'https://example.com/ads/tracking',
        ctaText: '开始查询',
        advertiserName: '包裹通',
        sortOrder: 9,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_09_click',
      },
      {
        slotKey: 'tools_text_10',
        type: 'text',
        enabled: true,
        title: '海外保险理赔',
        subtitle: '专业代办 快速到账',
        description: '平均理赔周期7天，成功率99%',
        href: 'https://example.com/ads/insurance-claim',
        ctaText: '提交理赔',
        advertiserName: '安心保',
        sortOrder: 10,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_10_click',
      },
      {
        slotKey: 'tools_text_11',
        type: 'text',
        enabled: true,
        title: '外贸B2B平台',
        subtitle: '连接全球采购商',
        description: '50万+活跃买家，年费低至999',
        href: 'https://example.com/ads/b2b-platform',
        ctaText: '入驻平台',
        tag: '招商',
        advertiserName: '全球贸易通',
        sortOrder: 11,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_11_click',
      },
      {
        slotKey: 'tools_text_12',
        type: 'text',
        enabled: true,
        title: '海外税务申报',
        subtitle: '美国/澳洲/加拿大',
        description: '在线报税，中文客服全程协助',
        href: 'https://example.com/ads/tax-filing',
        ctaText: '预约报税',
        advertiserName: '德信财税',
        sortOrder: 12,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_12_click',
      },
      {
        slotKey: 'tools_text_13',
        type: 'text',
        enabled: true,
        title: '留学贷款服务',
        subtitle: '最高100万 利率3.5%',
        description: '无需抵押，在读学生可申请',
        href: 'https://example.com/ads/study-loan',
        ctaText: '测算额度',
        advertiserName: '学贷通',
        sortOrder: 13,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_13_click',
      },
      {
        slotKey: 'tools_text_14',
        type: 'text',
        enabled: true,
        title: '海外租房平台',
        subtitle: '真实房源 无中介费',
        description: '覆盖30+国家，华人房东直租',
        href: 'https://example.com/ads/overseas-rental',
        ctaText: '查找房源',
        advertiserName: '安居海外',
        sortOrder: 14,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_14_click',
      },
      {
        slotKey: 'tools_text_15',
        type: 'text',
        enabled: true,
        title: '跨境法律咨询',
        subtitle: '中英双语律师',
        description: '合同纠纷/知识产权/劳动法',
        href: 'https://example.com/ads/legal',
        ctaText: '预约律师',
        advertiserName: '正义律所',
        sortOrder: 15,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_text_15_click',
      },
    ],
    imageAds: [
      {
        slotKey: 'tools_img_01',
        type: 'image',
        enabled: true,
        title: '集运专线特惠',
        subtitle: '首公斤仅¥19.9',
        imageUrl: '/images/ads/tools-shipping-promo.jpg',
        href: 'https://example.com/ads/shipping-promo',
        ctaText: '立即下单',
        advertiserName: '海运达',
        startAt: '2026-07-01',
        endAt: '2026-08-15',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_img_01_click',
      },
      {
        slotKey: 'tools_img_02',
        type: 'image',
        enabled: true,
        title: '海外银行开户',
        subtitle: '远程办理 3天到账',
        imageUrl: '/images/ads/tools-bank-account.jpg',
        href: 'https://example.com/ads/bank-account',
        ctaText: '预约开户',
        advertiserName: '全球金融通',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_img_02_click',
      },
      {
        slotKey: 'tools_img_03',
        type: 'image',
        enabled: true,
        title: '跨境电商ERP',
        subtitle: '多平台统一管理',
        imageUrl: '/images/ads/tools-ecommerce-erp.jpg',
        href: 'https://example.com/ads/ecommerce-erp',
        ctaText: '免费试用',
        advertiserName: '店小秘',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_img_03_click',
      },
      {
        slotKey: 'tools_img_04',
        type: 'image',
        enabled: false,
        title: '海外实习内推',
        subtitle: 'Google/Meta/Amazon',
        imageUrl: '/images/ads/tools-internship.jpg',
        href: 'https://example.com/ads/internship',
        ctaText: '查看岗位',
        advertiserName: '职通未来',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_img_04_click',
      },
      {
        slotKey: 'tools_img_05',
        type: 'image',
        enabled: true,
        title: '国际快递比价',
        subtitle: '一键对比 省钱50%',
        imageUrl: '/images/ads/tools-express-compare.jpg',
        href: 'https://example.com/ads/express-compare',
        ctaText: '开始比价',
        advertiserName: '快递100',
        sortOrder: 5,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'tools_img_05_click',
      },
    ],
  },
  {
    groupKey: 'home_after_task_chain_ad_group',
    title: '任务链下方广告位',
    description: '任务链流程完成后的广告展示',
    position: 'after_task_chain',
    enabled: true,
    showLabel: true,
    maxTextRows: 4,
    textColumns: 5,
    imageColumns: 5,
    mobileMode: 'compact',
    sortOrder: 30,
    textAds: [
      {
        slotKey: 'task_text_01',
        type: 'text',
        enabled: true,
        title: '海外商标注册',
        subtitle: '美/欧/日/韩全覆盖',
        description: '专业代理人，驳回免费重报',
        href: 'https://example.com/ads/trademark',
        ctaText: '查询商标',
        tag: '知识产权',
        advertiserName: '标易通',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_01_click',
      },
      {
        slotKey: 'task_text_02',
        type: 'text',
        enabled: true,
        title: '跨境独立站建站',
        subtitle: 'Shopify/WordPress定制',
        description: 'SEO优化+支付对接，7天上线',
        href: 'https://example.com/ads/website-build',
        ctaText: '获取方案',
        advertiserName: '建站之星',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_02_click',
      },
      {
        slotKey: 'task_text_03',
        type: 'text',
        enabled: true,
        title: '海外仓服务',
        subtitle: '美/英/德/澳四仓联动',
        description: '本地发货，时效提升80%',
        href: 'https://example.com/ads/overseas-warehouse',
        ctaText: '入仓咨询',
        tag: '物流',
        advertiserName: '万邑通',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_03_click',
      },
      {
        slotKey: 'task_text_04',
        type: 'text',
        enabled: true,
        title: '海外保险比价',
        subtitle: '医疗/旅行/财产险',
        description: '20+保险公司产品，一键对比',
        href: 'https://example.com/ads/insurance-compare',
        ctaText: '开始比价',
        advertiserName: '保险达人',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_04_click',
      },
      {
        slotKey: 'task_text_05',
        type: 'text',
        enabled: true,
        title: '外贸邮件营销',
        subtitle: 'EDM自动化获客',
        description: '日发10万封，打开率提升3倍',
        href: 'https://example.com/ads/email-marketing',
        ctaText: '免费试用',
        advertiserName: 'SendCloud',
        sortOrder: 5,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_05_click',
      },
      {
        slotKey: 'task_text_06',
        type: 'text',
        enabled: true,
        title: '海外社保公积金',
        subtitle: '代缴/转移/提取',
        description: '国内社保不断缴，海外安心工作',
        href: 'https://example.com/ads/social-security',
        ctaText: '了解详情',
        advertiserName: '人事无忧',
        sortOrder: 6,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_06_click',
      },
      {
        slotKey: 'task_text_07',
        type: 'text',
        enabled: true,
        title: '跨境直播带货',
        subtitle: 'TikTok/YouTube达人',
        description: '10万+海外KOL资源，ROI保证',
        href: 'https://example.com/ads/live-commerce',
        ctaText: '合作咨询',
        tag: '新渠道',
        advertiserName: '达人出海',
        sortOrder: 7,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_07_click',
      },
      {
        slotKey: 'task_text_08',
        type: 'text',
        enabled: false,
        title: '海外学历提升',
        subtitle: 'MBA/DBA在线硕士',
        description: '免联考，教育部认证',
        href: 'https://example.com/ads/online-mba',
        ctaText: '申请入学',
        advertiserName: '学途国际',
        sortOrder: 8,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_08_click',
      },
      {
        slotKey: 'task_text_09',
        type: 'text',
        enabled: true,
        title: '国际公证认证',
        subtitle: '海牙认证/领事认证',
        description: '线上提交，代办到底',
        href: 'https://example.com/ads/notary',
        ctaText: '提交材料',
        advertiserName: '公证通',
        sortOrder: 9,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_09_click',
      },
      {
        slotKey: 'task_text_10',
        type: 'text',
        enabled: true,
        title: '海外企业财税',
        subtitle: '记账/报税/审计',
        description: '中美会计准则，合规无忧',
        href: 'https://example.com/ads/business-tax',
        ctaText: '预约服务',
        advertiserName: '德信财税',
        sortOrder: 10,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_10_click',
      },
      {
        slotKey: 'task_text_11',
        type: 'text',
        enabled: true,
        title: '跨境供应链金融',
        subtitle: '应收账款融资',
        description: '最快24小时放款，额度500万',
        href: 'https://example.com/ads/supply-chain-finance',
        ctaText: '申请额度',
        advertiserName: '链融科技',
        sortOrder: 11,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_11_click',
      },
      {
        slotKey: 'task_text_12',
        type: 'text',
        enabled: true,
        title: '海外招聘平台',
        subtitle: '连接全球华人人才',
        description: '技术/金融/医疗高端岗位',
        href: 'https://example.com/ads/overseas-jobs',
        ctaText: '浏览职位',
        advertiserName: '海聘网',
        sortOrder: 12,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_12_click',
      },
      {
        slotKey: 'task_text_13',
        type: 'text',
        enabled: true,
        title: '外贸展会服务',
        subtitle: '广交会/CES/汉诺威',
        description: '展位预订+搭建+签证一站式',
        href: 'https://example.com/ads/trade-show',
        ctaText: '预订展位',
        advertiserName: '展通全球',
        sortOrder: 13,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_13_click',
      },
      {
        slotKey: 'task_text_14',
        type: 'text',
        enabled: true,
        title: '海外身份规划',
        subtitle: '绿卡/永居/护照',
        description: '多国身份方案，家族传承规划',
        href: 'https://example.com/ads/identity-plan',
        ctaText: '免费评估',
        tag: '高端',
        advertiserName: '金桥移民',
        sortOrder: 14,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_14_click',
      },
      {
        slotKey: 'task_text_15',
        type: 'text',
        enabled: true,
        title: '跨境数据分析',
        subtitle: '市场洞察/竞品监控',
        description: 'AI驱动，覆盖50+电商平台',
        href: 'https://example.com/ads/data-analytics',
        ctaText: '免费体验',
        advertiserName: '数跨境',
        sortOrder: 15,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_text_15_click',
      },
    ],
    imageAds: [
      {
        slotKey: 'task_img_01',
        type: 'image',
        enabled: true,
        title: '海外仓限时优惠',
        subtitle: '首月免仓储费',
        imageUrl: '/images/ads/task-overseas-warehouse.jpg',
        href: 'https://example.com/ads/warehouse-promo',
        ctaText: '立即入仓',
        advertiserName: '万邑通',
        startAt: '2026-07-01',
        endAt: '2026-09-30',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_img_01_click',
      },
      {
        slotKey: 'task_img_02',
        type: 'image',
        enabled: true,
        title: '跨境支付解决方案',
        subtitle: '一站式收单服务',
        imageUrl: '/images/ads/task-payment-solution.jpg',
        href: 'https://example.com/ads/payment-solution',
        ctaText: '开通服务',
        advertiserName: '汇付天下',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_img_02_click',
      },
      {
        slotKey: 'task_img_03',
        type: 'image',
        enabled: true,
        title: '留学申请季',
        subtitle: 'TOP50名校offer',
        imageUrl: '/images/ads/task-study-application.jpg',
        href: 'https://example.com/ads/study-application',
        ctaText: '免费咨询',
        advertiserName: '启航留学',
        startAt: '2026-07-15',
        endAt: '2026-10-15',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_img_03_click',
      },
      {
        slotKey: 'task_img_04',
        type: 'image',
        enabled: false,
        title: '海外保险套餐',
        subtitle: '全家保障计划',
        imageUrl: '/images/ads/task-insurance-package.jpg',
        href: 'https://example.com/ads/insurance-package',
        ctaText: '查看详情',
        advertiserName: '安心保',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_img_04_click',
      },
      {
        slotKey: 'task_img_05',
        type: 'image',
        enabled: true,
        title: 'TikTok Shop开店',
        subtitle: '东南亚/英美市场',
        imageUrl: '/images/ads/task-tiktok-shop.jpg',
        href: 'https://example.com/ads/tiktok-shop',
        ctaText: '立即入驻',
        advertiserName: '达人出海',
        sortOrder: 5,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'task_img_05_click',
      },
    ],
  },
  {
    groupKey: 'home_community_ad_group',
    title: '社区板块广告位',
    description: '社区互动区域的广告展示',
    position: 'community',
    enabled: true,
    showLabel: true,
    maxTextRows: 2,
    textColumns: 4,
    imageColumns: 4,
    mobileMode: 'compact',
    sortOrder: 40,
    textAds: [
      {
        slotKey: 'community_text_01',
        type: 'text',
        enabled: true,
        title: '华人相亲交友',
        subtitle: '真实认证 高质量',
        description: '50万+海外单身华人，找到你的TA',
        href: 'https://example.com/ads/dating',
        ctaText: '注册交友',
        tag: '社交',
        advertiserName: '缘聚海外',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_text_01_click',
      },
      {
        slotKey: 'community_text_02',
        type: 'text',
        enabled: true,
        title: '海外二手交易',
        subtitle: '华人闲置好物',
        description: '家具/电器/教材/母婴用品',
        href: 'https://example.com/ads/second-hand',
        ctaText: '发布闲置',
        advertiserName: '华人之家',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_text_02_click',
      },
      {
        slotKey: 'community_text_03',
        type: 'text',
        enabled: true,
        title: '海外拼车出行',
        subtitle: '同城/跨城/机场接送',
        description: '安全认证司机，费用AA更省钱',
        href: 'https://example.com/ads/carpool',
        ctaText: '发布行程',
        advertiserName: '同行出行',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_text_03_click',
      },
      {
        slotKey: 'community_text_04',
        type: 'text',
        enabled: true,
        title: '海外美食团购',
        subtitle: '家乡味道 产地直发',
        description: '零食/调料/生鲜，满$49包邮',
        href: 'https://example.com/ads/food-group-buy',
        ctaText: '去逛逛',
        tag: '美食',
        advertiserName: '味觉乡愁',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_text_04_click',
      },
      {
        slotKey: 'community_text_05',
        type: 'text',
        enabled: true,
        title: '华人活动发布',
        subtitle: '线下聚会/讲座/展览',
        description: '发现身边的华人活动，拓展人脉',
        href: 'https://example.com/ads/events',
        ctaText: '发布活动',
        advertiserName: '华人之家',
        sortOrder: 5,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_text_05_click',
      },
      {
        slotKey: 'community_text_06',
        type: 'text',
        enabled: false,
        title: '海外宠物服务',
        subtitle: '寄养/美容/医疗',
        description: '华人宠物店推荐，中文沟通',
        href: 'https://example.com/ads/pet-service',
        ctaText: '查找附近',
        advertiserName: '爱宠联盟',
        sortOrder: 6,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_text_06_click',
      },
      {
        slotKey: 'community_text_07',
        type: 'text',
        enabled: true,
        title: '华人律师咨询',
        subtitle: '移民/房产/劳动纠纷',
        description: '首次咨询免费，中英双语服务',
        href: 'https://example.com/ads/lawyer',
        ctaText: '预约咨询',
        advertiserName: '正义律所',
        sortOrder: 7,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_text_07_click',
      },
      {
        slotKey: 'community_text_08',
        type: 'text',
        enabled: true,
        title: '海外补习辅导',
        subtitle: 'K-12/大学课程',
        description: '名校学霸一对一，提分保障',
        href: 'https://example.com/ads/tutoring',
        ctaText: '预约试听',
        tag: '教育',
        advertiserName: '学霸帮',
        sortOrder: 8,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_text_08_click',
      },
    ],
    imageAds: [
      {
        slotKey: 'community_img_01',
        type: 'image',
        enabled: true,
        title: '华人春晚门票',
        subtitle: '2026海外华人春晚',
        imageUrl: '/images/ads/community-spring-gala.jpg',
        href: 'https://example.com/ads/spring-gala',
        ctaText: '购票入场',
        advertiserName: '华人文化协会',
        startAt: '2026-07-01',
        endAt: '2026-08-01',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_img_01_click',
      },
      {
        slotKey: 'community_img_02',
        type: 'image',
        enabled: true,
        title: '家乡特产直邮',
        subtitle: '中秋月饼礼盒',
        imageUrl: '/images/ads/community-mooncake.jpg',
        href: 'https://example.com/ads/mooncake',
        ctaText: '立即订购',
        advertiserName: '味觉乡愁',
        startAt: '2026-08-01',
        endAt: '2026-09-30',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_img_02_click',
      },
      {
        slotKey: 'community_img_03',
        type: 'image',
        enabled: true,
        title: '华人招聘会',
        subtitle: '500+企业现场面试',
        imageUrl: '/images/ads/community-job-fair.jpg',
        href: 'https://example.com/ads/job-fair',
        ctaText: '报名参加',
        advertiserName: '海聘网',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_img_03_click',
      },
      {
        slotKey: 'community_img_04',
        type: 'image',
        enabled: false,
        title: '中文学校招生',
        subtitle: '周末班/在线班',
        imageUrl: '/images/ads/community-chinese-school.jpg',
        href: 'https://example.com/ads/chinese-school',
        ctaText: '报名咨询',
        advertiserName: '华文教育',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'community_img_04_click',
      },
    ],
  },
  {
    groupKey: 'home_before_footer_ad_group',
    title: '页脚上方广告位',
    description: '页面底部的大容量广告展示区',
    position: 'before_footer',
    enabled: true,
    showLabel: true,
    maxTextRows: 5,
    textColumns: 6,
    imageColumns: 6,
    mobileMode: 'full',
    sortOrder: 50,
    textAds: [
      {
        slotKey: 'footer_text_01',
        type: 'text',
        enabled: true,
        title: '国际快递比价平台',
        subtitle: 'DHL/FedEx/UPS最低价',
        description: '一键比价，最高省60%运费',
        href: 'https://example.com/ads/express-compare-2',
        ctaText: '立即比价',
        tag: '省钱',
        advertiserName: '快递100',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_01_click',
      },
      {
        slotKey: 'footer_text_02',
        type: 'text',
        enabled: true,
        title: '海外公司注册代理',
        subtitle: 'BVI/开曼/塞舌尔',
        description: '离岸公司设立，税务优化方案',
        href: 'https://example.com/ads/offshore-company',
        ctaText: '免费咨询',
        advertiserName: '环球商务',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_02_click',
      },
      {
        slotKey: 'footer_text_03',
        type: 'text',
        enabled: true,
        title: '跨境电商ERP系统',
        subtitle: '多平台/多店铺管理',
        description: '订单/库存/物流/财务一体化',
        href: 'https://example.com/ads/erp-system',
        ctaText: '免费试用',
        tag: '效率',
        advertiserName: '店小秘',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_03_click',
      },
      {
        slotKey: 'footer_text_04',
        type: 'text',
        enabled: true,
        title: '海外签证代办',
        subtitle: '旅游/商务/探亲签证',
        description: '拒签退款，材料简化，出签快',
        href: 'https://example.com/ads/visa-service',
        ctaText: '在线申请',
        advertiserName: '签证通',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_04_click',
      },
      {
        slotKey: 'footer_text_05',
        type: 'text',
        enabled: true,
        title: '外贸客户开发',
        subtitle: '海关数据+LinkedIn',
        description: '精准获客工具，月增1000+询盘',
        href: 'https://example.com/ads/customer-dev',
        ctaText: '获取方案',
        advertiserName: '外贸邦',
        sortOrder: 5,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_05_click',
      },
      {
        slotKey: 'footer_text_06',
        type: 'text',
        enabled: true,
        title: '海外保险直购',
        subtitle: '港险/新加坡保险',
        description: '重疾险/储蓄险/医疗险，保费省30%',
        href: 'https://example.com/ads/hk-insurance',
        ctaText: '预约顾问',
        tag: '热门',
        advertiserName: '保通全球',
        sortOrder: 6,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_06_click',
      },
      {
        slotKey: 'footer_text_07',
        type: 'text',
        enabled: true,
        title: '留学文书润色',
        subtitle: 'Native Speaker修改',
        description: 'PS/CV/RL，哈佛导师团队',
        href: 'https://example.com/ads/essay-editing',
        ctaText: '提交文书',
        advertiserName: '文优留学',
        sortOrder: 7,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_07_click',
      },
      {
        slotKey: 'footer_text_08',
        type: 'text',
        enabled: true,
        title: '海外税务合规',
        subtitle: 'FATCA/CRS申报',
        description: '全球税务信息交换合规咨询',
        href: 'https://example.com/ads/tax-compliance',
        ctaText: '预约咨询',
        advertiserName: '德信财税',
        sortOrder: 8,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_08_click',
      },
      {
        slotKey: 'footer_text_09',
        type: 'text',
        enabled: true,
        title: '跨境物流保险',
        subtitle: '货损/丢件全额赔',
        description: '每票最低¥1起，理赔48小时到账',
        href: 'https://example.com/ads/logistics-insurance',
        ctaText: '立即投保',
        advertiserName: '货运保',
        sortOrder: 9,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_09_click',
      },
      {
        slotKey: 'footer_text_10',
        type: 'text',
        enabled: false,
        title: '海外云服务器',
        subtitle: '美/日/新/德节点',
        description: 'CN2 GIA线路，延迟低至30ms',
        href: 'https://example.com/ads/cloud-server',
        ctaText: '立即购买',
        advertiserName: '云际互联',
        sortOrder: 10,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_10_click',
      },
      {
        slotKey: 'footer_text_11',
        type: 'text',
        enabled: true,
        title: '海外代购平台',
        subtitle: '亚马逊/ebay代拍',
        description: '手续费低至3%，正品保障',
        href: 'https://example.com/ads/daigou',
        ctaText: '开始代购',
        advertiserName: '海淘帮',
        sortOrder: 11,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_11_click',
      },
      {
        slotKey: 'footer_text_12',
        type: 'text',
        enabled: true,
        title: '外贸独立站SEO',
        subtitle: 'Google排名优化',
        description: '6个月上首页，无效退款',
        href: 'https://example.com/ads/seo-service',
        ctaText: '免费诊断',
        tag: '推广',
        advertiserName: '搜外优化',
        sortOrder: 12,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_12_click',
      },
      {
        slotKey: 'footer_text_13',
        type: 'text',
        enabled: true,
        title: '海外投资移民',
        subtitle: '希腊/葡萄牙/加勒比',
        description: '买房移民，全家获身份',
        href: 'https://example.com/ads/investment-immigration',
        ctaText: '免费评估',
        advertiserName: '金桥移民',
        sortOrder: 13,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_13_click',
      },
      {
        slotKey: 'footer_text_14',
        type: 'text',
        enabled: true,
        title: '跨境收款账户',
        subtitle: '多币种虚拟账户',
        description: '0开户费，支持USD/EUR/GBP',
        href: 'https://example.com/ads/virtual-account',
        ctaText: '注册账户',
        advertiserName: 'PingPong',
        sortOrder: 14,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_14_click',
      },
      {
        slotKey: 'footer_text_15',
        type: 'text',
        enabled: true,
        title: '海外学历认证代办',
        subtitle: '留服中心认证',
        description: '30天出结果，不成功退款',
        href: 'https://example.com/ads/degree-cert-2',
        ctaText: '提交认证',
        advertiserName: '学信国际',
        sortOrder: 15,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_15_click',
      },
      {
        slotKey: 'footer_text_16',
        type: 'text',
        enabled: true,
        title: '外贸B2B建站',
        subtitle: '询盘型网站定制',
        description: 'Google Ads对接，转化率提升200%',
        href: 'https://example.com/ads/b2b-website',
        ctaText: '获取报价',
        advertiserName: '建站之星',
        sortOrder: 16,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_16_click',
      },
      {
        slotKey: 'footer_text_17',
        type: 'text',
        enabled: true,
        title: '海外华人律师',
        subtitle: '24小时在线咨询',
        description: '移民/商业/家庭法律全覆盖',
        href: 'https://example.com/ads/online-lawyer',
        ctaText: '立即咨询',
        advertiserName: '正义律所',
        sortOrder: 17,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_17_click',
      },
      {
        slotKey: 'footer_text_18',
        type: 'text',
        enabled: false,
        title: '国际搬家服务',
        subtitle: '门到门全程无忧',
        description: '专业打包，海运/空运可选',
        href: 'https://example.com/ads/international-moving',
        ctaText: '获取报价',
        advertiserName: '七海搬家',
        sortOrder: 18,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_18_click',
      },
      {
        slotKey: 'footer_text_19',
        type: 'text',
        enabled: true,
        title: '海外实习推荐',
        subtitle: '华尔街/硅谷/伦敦',
        description: '名企内推，简历直达HR',
        href: 'https://example.com/ads/internship-recommend',
        ctaText: '投递简历',
        advertiserName: '职通未来',
        sortOrder: 19,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_19_click',
      },
      {
        slotKey: 'footer_text_20',
        type: 'text',
        enabled: true,
        title: '跨境直播培训',
        subtitle: 'TikTok/Amazon Live',
        description: '从0到月销10万刀，实战教学',
        href: 'https://example.com/ads/live-training',
        ctaText: '报名学习',
        tag: '课程',
        advertiserName: '出海商学院',
        sortOrder: 20,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_20_click',
      },
      {
        slotKey: 'footer_text_21',
        type: 'text',
        enabled: true,
        title: '海外商标注册',
        subtitle: '全球190+国家',
        description: '智能检索+专业代理，通过率98%',
        href: 'https://example.com/ads/trademark-global',
        ctaText: '免费检索',
        advertiserName: '标易通',
        sortOrder: 21,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_21_click',
      },
      {
        slotKey: 'footer_text_22',
        type: 'text',
        enabled: true,
        title: '外贸单证服务',
        subtitle: '报关/产地证/商检',
        description: '电子口岸对接，当日出证',
        href: 'https://example.com/ads/trade-docs',
        ctaText: '在线下单',
        advertiserName: '通关达',
        sortOrder: 22,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_22_click',
      },
      {
        slotKey: 'footer_text_23',
        type: 'text',
        enabled: true,
        title: '海外华人理财',
        subtitle: '美元/港币定存',
        description: '年化5%+，FDIC保障',
        href: 'https://example.com/ads/overseas-finance',
        ctaText: '开始理财',
        advertiserName: '全球金融通',
        sortOrder: 23,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_23_click',
      },
      {
        slotKey: 'footer_text_24',
        type: 'text',
        enabled: true,
        title: '跨境电商物流',
        subtitle: 'FBA头程/海外仓',
        description: '美线快船12天入仓，价格透明',
        href: 'https://example.com/ads/fba-shipping',
        ctaText: '获取报价',
        tag: '物流',
        advertiserName: '纵腾集团',
        sortOrder: 24,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_text_24_click',
      },
    ],
    imageAds: [
      {
        slotKey: 'footer_img_01',
        type: 'image',
        enabled: true,
        title: '黑五物流大促',
        subtitle: '全线路8折起',
        imageUrl: '/images/ads/footer-black-friday-logistics.jpg',
        href: 'https://example.com/ads/footer-black-friday',
        ctaText: '查看详情',
        advertiserName: '速达国际',
        startAt: '2026-07-01',
        endAt: '2026-08-31',
        sortOrder: 1,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_img_01_click',
      },
      {
        slotKey: 'footer_img_02',
        type: 'image',
        enabled: true,
        title: '港险投保季',
        subtitle: '重疾险保费优惠20%',
        imageUrl: '/images/ads/footer-hk-insurance.jpg',
        href: 'https://example.com/ads/footer-hk-insurance',
        ctaText: '预约顾问',
        advertiserName: '保通全球',
        startAt: '2026-07-15',
        endAt: '2026-09-15',
        sortOrder: 2,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_img_02_click',
      },
      {
        slotKey: 'footer_img_03',
        type: 'image',
        enabled: true,
        title: '跨境电商峰会',
        subtitle: '2026深圳站',
        imageUrl: '/images/ads/footer-ecommerce-summit.jpg',
        href: 'https://example.com/ads/footer-summit',
        ctaText: '立即报名',
        advertiserName: '出海商学院',
        sortOrder: 3,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_img_03_click',
      },
      {
        slotKey: 'footer_img_04',
        type: 'image',
        enabled: false,
        title: '海外房产展',
        subtitle: '全球精选楼盘',
        imageUrl: '/images/ads/footer-property-expo.jpg',
        href: 'https://example.com/ads/footer-property-expo',
        ctaText: '预约参观',
        advertiserName: '环球置业',
        sortOrder: 4,
        displayDevices: ['desktop', 'tablet'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_img_04_click',
      },
      {
        slotKey: 'footer_img_05',
        type: 'image',
        enabled: true,
        title: '留学展2026',
        subtitle: '100+院校现场面试',
        imageUrl: '/images/ads/footer-study-expo.jpg',
        href: 'https://example.com/ads/footer-study-expo',
        ctaText: '免费索票',
        advertiserName: '启航留学',
        startAt: '2026-08-01',
        endAt: '2026-10-31',
        sortOrder: 5,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_img_05_click',
      },
      {
        slotKey: 'footer_img_06',
        type: 'image',
        enabled: true,
        title: '跨境支付优惠',
        subtitle: '新客首笔免手续费',
        imageUrl: '/images/ads/footer-payment-promo.jpg',
        href: 'https://example.com/ads/footer-payment-promo',
        ctaText: '立即开通',
        advertiserName: 'PingPong',
        sortOrder: 6,
        displayDevices: ['desktop', 'tablet', 'mobile'],
        nofollow: true,
        sponsored: true,
        trackingKey: 'footer_img_06_click',
      },
    ],
  },
];
